const CUSTOMER_ELIGIBLE = "CUSTOMER_ELIGIBLE";
const CUSTOMER_INELIGIBLE = "CUSTOMER_INELIGIBLE";
const TECHNICAL_FAILURE = "TECHNICAL_FAILURE";
const INVALID_ACCOUNT_NUMBER = "INVALID_ACCOUNT_NUMBER";

const SPORTS_CHANNEL = "SPORTS";
const KIDS_CHANNEL = "KIDS";
const MUSIC_CHANNEL = "MUSIC";
const NEWS_CHANNEL = "NEWS";
const MOVIES_CHANNEL = "MOVIES";

const CHAMPIONS_LEAGUE_FINAL_TICKET = "CHAMPIONS_LEAGUE_FINAL_TICKET";
const KARAOKE_PRO_MICROPHONE = "KARAOKE_PRO_MICROPHONE";
const PIRATES_OF_THE_CARRIBEAN_COLLECTION =
  "PIRATES_OF_THE_CARIBBEAN_COLLECTION";

const rewardsMap = {
  [SPORTS_CHANNEL]: [CHAMPIONS_LEAGUE_FINAL_TICKET],
  [KIDS_CHANNEL]: [],
  [MUSIC_CHANNEL]: [KARAOKE_PRO_MICROPHONE],
  [NEWS_CHANNEL]: [],
  [MOVIES_CHANNEL]: [PIRATES_OF_THE_CARRIBEAN_COLLECTION],
};

module.exports = {
  CUSTOMER_ELIGIBLE,
  CUSTOMER_INELIGIBLE,
  TECHNICAL_FAILURE,
  INVALID_ACCOUNT_NUMBER,
  SPORTS_CHANNEL,
  KIDS_CHANNEL,
  MUSIC_CHANNEL,
  NEWS_CHANNEL,
  MOVIES_CHANNEL,
  CHAMPIONS_LEAGUE_FINAL_TICKET,
  KARAOKE_PRO_MICROPHONE,
  PIRATES_OF_THE_CARRIBEAN_COLLECTION,
  rewardsMap,
};
